"""
Konfiguration und Stammdaten für das Deep Learning Absolventenprojekt.
Generiert aus dem Originalskript mit Erweiterungen (Turnus, Zeitkonto).
"""

CONFIG = {   'anomalie_quote': 0.05,
    'csv_decimal': '.',
    'csv_encoding': 'utf-8',
    'csv_sep': ',',
    'end_jahr': 2024,
    'gewicht_erwerb': 0.006,
    'gewicht_hzb': 0.4,
    'gewicht_integration': 0.2,
    'gewicht_integration_erstakademiker': 0.05,
    'gewicht_integration_erwerb': 0.003,
    'gewicht_integration_migration': 0.05,
    'gewicht_integration_rauschen': 0.25,
    'gewicht_lerneffekt': 0.2,
    'gewicht_motivation': 0.5,
    'gewicht_motivation_erwerb': 0.004,
    'gewicht_motivation_hzb': 0.08,
    'gewicht_motivation_rauschen': 0.25,
    'gewicht_rauschen': 0.18,
    'gewicht_schwierigkeit': 0.3,
    'gewicht_support_boost': 0.04,
    'integration_startwert': 0.65,
    'leistung_startwert': 0.55,
    'log_every_n_studis': 1000,
    'max_simulations_semester': 16,
    'motivation_startwert': 0.65,
    'n_studierende': 50000,
    'output_dir': '../output_dl',
    'seed': 42,
    'start_jahr': 2015,
    'support_deckel': 0.15,
    'zeitkonto_budget_h': 900}

MODULE_CURRICULA = {   'SG01': [   {   'cp': 9,
                    'fachsem': 1,
                    'name': 'Programmierung I',
                    'pflicht': True,
                    'schwierigkeit': 0.55,
                    'turnus': 'WS',
                    'workload_h': 270},
                {   'cp': 9,
                    'fachsem': 1,
                    'name': 'Mathematik I',
                    'pflicht': True,
                    'schwierigkeit': 0.75,
                    'turnus': 'WS',
                    'workload_h': 270},
                {   'cp': 6,
                    'fachsem': 1,
                    'name': 'Technische Informatik',
                    'pflicht': True,
                    'schwierigkeit': 0.5,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 9,
                    'fachsem': 2,
                    'name': 'Programmierung II',
                    'pflicht': True,
                    'schwierigkeit': 0.6,
                    'turnus': 'SS',
                    'workload_h': 270},
                {   'cp': 9,
                    'fachsem': 2,
                    'name': 'Mathematik II',
                    'pflicht': True,
                    'schwierigkeit': 0.8,
                    'turnus': 'SS',
                    'workload_h': 270},
                {   'cp': 6,
                    'fachsem': 3,
                    'name': 'Datenbanken',
                    'pflicht': True,
                    'schwierigkeit': 0.45,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 9,
                    'fachsem': 3,
                    'name': 'Algorithmen',
                    'pflicht': True,
                    'schwierigkeit': 0.7,
                    'turnus': 'WS',
                    'workload_h': 270},
                {   'cp': 6,
                    'fachsem': 4,
                    'name': 'Software Engineering',
                    'pflicht': True,
                    'schwierigkeit': 0.5,
                    'turnus': 'SS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 4,
                    'name': 'Betriebssysteme',
                    'pflicht': True,
                    'schwierigkeit': 0.65,
                    'turnus': 'SS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 4,
                    'name': 'Statistik',
                    'pflicht': True,
                    'schwierigkeit': 0.65,
                    'turnus': 'SS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 5,
                    'name': 'Rechnernetze',
                    'pflicht': True,
                    'schwierigkeit': 0.55,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 9,
                    'fachsem': 5,
                    'name': 'Theoretische Inf.',
                    'pflicht': True,
                    'schwierigkeit': 0.85,
                    'turnus': 'WS',
                    'workload_h': 270},
                {   'cp': 6,
                    'fachsem': 5,
                    'name': 'Wahlpflicht KI',
                    'pflicht': False,
                    'schwierigkeit': 0.6,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 9,
                    'fachsem': 6,
                    'name': 'Projektarbeit',
                    'pflicht': True,
                    'schwierigkeit': 0.45,
                    'turnus': 'beides',
                    'workload_h': 270},
                {   'cp': 12,
                    'fachsem': 6,
                    'name': 'Bachelorarbeit',
                    'pflicht': True,
                    'schwierigkeit': 0.55,
                    'turnus': 'beides',
                    'workload_h': 360},
                {   'cp': 3,
                    'fachsem': 6,
                    'name': 'Seminar Informatik',
                    'pflicht': True,
                    'schwierigkeit': 0.35,
                    'turnus': 'SS',
                    'workload_h': 90}],
    'SG02': [   {   'cp': 6,
                    'fachsem': 1,
                    'name': 'Grundlagen BWL',
                    'pflicht': True,
                    'schwierigkeit': 0.35,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 9,
                    'fachsem': 1,
                    'name': 'Mathematik f. WiWi',
                    'pflicht': True,
                    'schwierigkeit': 0.7,
                    'turnus': 'WS',
                    'workload_h': 270},
                {   'cp': 6,
                    'fachsem': 1,
                    'name': 'Buchführung',
                    'pflicht': True,
                    'schwierigkeit': 0.5,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 2,
                    'name': 'Mikroökonomie',
                    'pflicht': True,
                    'schwierigkeit': 0.55,
                    'turnus': 'SS',
                    'workload_h': 180},
                {   'cp': 9,
                    'fachsem': 2,
                    'name': 'Statistik I',
                    'pflicht': True,
                    'schwierigkeit': 0.7,
                    'turnus': 'SS',
                    'workload_h': 270},
                {   'cp': 6,
                    'fachsem': 2,
                    'name': 'Kostenrechnung',
                    'pflicht': True,
                    'schwierigkeit': 0.5,
                    'turnus': 'SS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 3,
                    'name': 'Makroökonomie',
                    'pflicht': True,
                    'schwierigkeit': 0.55,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 3,
                    'name': 'Marketing',
                    'pflicht': True,
                    'schwierigkeit': 0.35,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 3,
                    'name': 'Statistik II',
                    'pflicht': True,
                    'schwierigkeit': 0.75,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 4,
                    'name': 'Finanzierung',
                    'pflicht': True,
                    'schwierigkeit': 0.6,
                    'turnus': 'SS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 4,
                    'name': 'Personalwirtschaft',
                    'pflicht': True,
                    'schwierigkeit': 0.35,
                    'turnus': 'SS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 4,
                    'name': 'Wirtschaftsrecht',
                    'pflicht': True,
                    'schwierigkeit': 0.55,
                    'turnus': 'SS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 5,
                    'name': 'Wahlpflicht Controlling',
                    'pflicht': False,
                    'schwierigkeit': 0.55,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 5,
                    'name': 'Wahlpflicht Steuern',
                    'pflicht': False,
                    'schwierigkeit': 0.65,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 5,
                    'name': 'Seminar BWL',
                    'pflicht': True,
                    'schwierigkeit': 0.4,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 12,
                    'fachsem': 6,
                    'name': 'Bachelorarbeit',
                    'pflicht': True,
                    'schwierigkeit': 0.5,
                    'turnus': 'beides',
                    'workload_h': 360},
                {   'cp': 12,
                    'fachsem': 6,
                    'name': 'Praxisprojekt',
                    'pflicht': True,
                    'schwierigkeit': 0.35,
                    'turnus': 'beides',
                    'workload_h': 360}],
    'SG03': [   {   'cp': 9,
                    'fachsem': 1,
                    'name': 'Mathematik I',
                    'pflicht': True,
                    'schwierigkeit': 0.72,
                    'turnus': 'WS',
                    'workload_h': 270},
                {   'cp': 9,
                    'fachsem': 1,
                    'name': 'Technische Mechanik I',
                    'pflicht': True,
                    'schwierigkeit': 0.65,
                    'turnus': 'WS',
                    'workload_h': 270},
                {   'cp': 6,
                    'fachsem': 1,
                    'name': 'Konstruktion I',
                    'pflicht': True,
                    'schwierigkeit': 0.55,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 9,
                    'fachsem': 2,
                    'name': 'Mathematik II',
                    'pflicht': True,
                    'schwierigkeit': 0.75,
                    'turnus': 'SS',
                    'workload_h': 270},
                {   'cp': 9,
                    'fachsem': 2,
                    'name': 'Technische Mechanik II',
                    'pflicht': True,
                    'schwierigkeit': 0.72,
                    'turnus': 'SS',
                    'workload_h': 270},
                {   'cp': 6,
                    'fachsem': 2,
                    'name': 'Werkstoffkunde',
                    'pflicht': True,
                    'schwierigkeit': 0.6,
                    'turnus': 'SS',
                    'workload_h': 180},
                {   'cp': 9,
                    'fachsem': 3,
                    'name': 'Thermodynamik',
                    'pflicht': True,
                    'schwierigkeit': 0.72,
                    'turnus': 'WS',
                    'workload_h': 270},
                {   'cp': 6,
                    'fachsem': 3,
                    'name': 'Konstruktion II',
                    'pflicht': True,
                    'schwierigkeit': 0.6,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 3,
                    'name': 'Elektrotechnik',
                    'pflicht': True,
                    'schwierigkeit': 0.65,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 9,
                    'fachsem': 4,
                    'name': 'Strömungslehre',
                    'pflicht': True,
                    'schwierigkeit': 0.72,
                    'turnus': 'SS',
                    'workload_h': 270},
                {   'cp': 6,
                    'fachsem': 4,
                    'name': 'Fertigungstechnik',
                    'pflicht': True,
                    'schwierigkeit': 0.55,
                    'turnus': 'SS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 4,
                    'name': 'Regelungstechnik',
                    'pflicht': True,
                    'schwierigkeit': 0.7,
                    'turnus': 'SS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 5,
                    'name': 'Maschinendynamik',
                    'pflicht': True,
                    'schwierigkeit': 0.75,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 5,
                    'name': 'CAD/Simulation',
                    'pflicht': True,
                    'schwierigkeit': 0.5,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 5,
                    'name': 'Wahlpflicht Antriebe',
                    'pflicht': False,
                    'schwierigkeit': 0.65,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 15,
                    'fachsem': 6,
                    'name': 'Industriepraktikum',
                    'pflicht': True,
                    'schwierigkeit': 0.35,
                    'turnus': 'SS',
                    'workload_h': 450},
                {   'cp': 9,
                    'fachsem': 6,
                    'name': 'Projektarbeit',
                    'pflicht': True,
                    'schwierigkeit': 0.55,
                    'turnus': 'beides',
                    'workload_h': 270},
                {   'cp': 15,
                    'fachsem': 7,
                    'name': 'Bachelorarbeit',
                    'pflicht': True,
                    'schwierigkeit': 0.6,
                    'turnus': 'beides',
                    'workload_h': 450},
                {   'cp': 6,
                    'fachsem': 7,
                    'name': 'Seminar Maschinenbau',
                    'pflicht': True,
                    'schwierigkeit': 0.4,
                    'turnus': 'WS',
                    'workload_h': 180}],
    'SG04': [   {   'cp': 6,
                    'fachsem': 1,
                    'name': 'Einführung Psychologie',
                    'pflicht': True,
                    'schwierigkeit': 0.35,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 9,
                    'fachsem': 1,
                    'name': 'Statistik I',
                    'pflicht': True,
                    'schwierigkeit': 0.75,
                    'turnus': 'WS',
                    'workload_h': 270},
                {   'cp': 6,
                    'fachsem': 1,
                    'name': 'Biopsychologie',
                    'pflicht': True,
                    'schwierigkeit': 0.55,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 9,
                    'fachsem': 2,
                    'name': 'Allg. Psychologie I',
                    'pflicht': True,
                    'schwierigkeit': 0.55,
                    'turnus': 'SS',
                    'workload_h': 270},
                {   'cp': 9,
                    'fachsem': 2,
                    'name': 'Statistik II',
                    'pflicht': True,
                    'schwierigkeit': 0.8,
                    'turnus': 'SS',
                    'workload_h': 270},
                {   'cp': 6,
                    'fachsem': 2,
                    'name': 'Methodenlehre',
                    'pflicht': True,
                    'schwierigkeit': 0.7,
                    'turnus': 'SS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 3,
                    'name': 'Sozialpsychologie',
                    'pflicht': True,
                    'schwierigkeit': 0.45,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 3,
                    'name': 'Entwicklungspsychologie',
                    'pflicht': True,
                    'schwierigkeit': 0.45,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 9,
                    'fachsem': 3,
                    'name': 'Diagnostik I',
                    'pflicht': True,
                    'schwierigkeit': 0.65,
                    'turnus': 'WS',
                    'workload_h': 270},
                {   'cp': 9,
                    'fachsem': 4,
                    'name': 'Klinische Psychologie',
                    'pflicht': True,
                    'schwierigkeit': 0.55,
                    'turnus': 'SS',
                    'workload_h': 270},
                {   'cp': 6,
                    'fachsem': 4,
                    'name': 'Diagnostik II',
                    'pflicht': True,
                    'schwierigkeit': 0.65,
                    'turnus': 'SS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 4,
                    'name': 'Pädagogische Psych.',
                    'pflicht': True,
                    'schwierigkeit': 0.45,
                    'turnus': 'SS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 5,
                    'name': 'Arbeits- u. Org.-Psych.',
                    'pflicht': True,
                    'schwierigkeit': 0.5,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 5,
                    'name': 'Wahlpflicht Forschung',
                    'pflicht': False,
                    'schwierigkeit': 0.6,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 9,
                    'fachsem': 5,
                    'name': 'Empirisches Praktikum',
                    'pflicht': True,
                    'schwierigkeit': 0.6,
                    'turnus': 'WS',
                    'workload_h': 270},
                {   'cp': 6,
                    'fachsem': 6,
                    'name': 'Seminar Psychologie',
                    'pflicht': True,
                    'schwierigkeit': 0.4,
                    'turnus': 'SS',
                    'workload_h': 180},
                {   'cp': 12,
                    'fachsem': 6,
                    'name': 'Bachelorarbeit',
                    'pflicht': True,
                    'schwierigkeit': 0.55,
                    'turnus': 'beides',
                    'workload_h': 360},
                {   'cp': 6,
                    'fachsem': 6,
                    'name': 'Berufspraktikum',
                    'pflicht': True,
                    'schwierigkeit': 0.3,
                    'turnus': 'SS',
                    'workload_h': 180}],
    'SG05': [   {   'cp': 6,
                    'fachsem': 1,
                    'name': 'Einführung Soz. Arbeit',
                    'pflicht': True,
                    'schwierigkeit': 0.3,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 1,
                    'name': 'Soziologie',
                    'pflicht': True,
                    'schwierigkeit': 0.45,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 1,
                    'name': 'Recht I',
                    'pflicht': True,
                    'schwierigkeit': 0.6,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 2,
                    'name': 'Psychologie f. SozArb',
                    'pflicht': True,
                    'schwierigkeit': 0.45,
                    'turnus': 'SS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 2,
                    'name': 'Pädagogik',
                    'pflicht': True,
                    'schwierigkeit': 0.4,
                    'turnus': 'SS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 2,
                    'name': 'Recht II',
                    'pflicht': True,
                    'schwierigkeit': 0.65,
                    'turnus': 'SS',
                    'workload_h': 180},
                {   'cp': 9,
                    'fachsem': 3,
                    'name': 'Methoden Soz. Arbeit I',
                    'pflicht': True,
                    'schwierigkeit': 0.45,
                    'turnus': 'WS',
                    'workload_h': 270},
                {   'cp': 6,
                    'fachsem': 3,
                    'name': 'Statistik/Empirie',
                    'pflicht': True,
                    'schwierigkeit': 0.7,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 3,
                    'name': 'Handlungsfelder I',
                    'pflicht': True,
                    'schwierigkeit': 0.4,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 9,
                    'fachsem': 4,
                    'name': 'Methoden Soz. Arbeit II',
                    'pflicht': True,
                    'schwierigkeit': 0.5,
                    'turnus': 'SS',
                    'workload_h': 270},
                {   'cp': 15,
                    'fachsem': 4,
                    'name': 'Praxissemester I',
                    'pflicht': True,
                    'schwierigkeit': 0.35,
                    'turnus': 'SS',
                    'workload_h': 450},
                {   'cp': 6,
                    'fachsem': 5,
                    'name': 'Ethik',
                    'pflicht': True,
                    'schwierigkeit': 0.4,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 5,
                    'name': 'Handlungsfelder II',
                    'pflicht': True,
                    'schwierigkeit': 0.45,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 6,
                    'fachsem': 5,
                    'name': 'Wahlpflicht Beratung',
                    'pflicht': False,
                    'schwierigkeit': 0.45,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 15,
                    'fachsem': 6,
                    'name': 'Praxissemester II',
                    'pflicht': True,
                    'schwierigkeit': 0.35,
                    'turnus': 'SS',
                    'workload_h': 450},
                {   'cp': 9,
                    'fachsem': 6,
                    'name': 'Forschungsprojekt',
                    'pflicht': True,
                    'schwierigkeit': 0.55,
                    'turnus': 'beides',
                    'workload_h': 270},
                {   'cp': 6,
                    'fachsem': 7,
                    'name': 'Seminar Soz. Arbeit',
                    'pflicht': True,
                    'schwierigkeit': 0.4,
                    'turnus': 'WS',
                    'workload_h': 180},
                {   'cp': 12,
                    'fachsem': 7,
                    'name': 'Bachelorarbeit',
                    'pflicht': True,
                    'schwierigkeit': 0.5,
                    'turnus': 'beides',
                    'workload_h': 360},
                {   'cp': 3,
                    'fachsem': 7,
                    'name': 'Kolloquium',
                    'pflicht': True,
                    'schwierigkeit': 0.3,
                    'turnus': 'beides',
                    'workload_h': 90}]}

STUDIENGAENGE = [   {   'abschluss': 'Bachelor',
        'cp_gesamt': 120,
        'name': 'Informatik',
        'regelstudienzeit': 6,
        'studiengang_id': 'SG01'},
    {   'abschluss': 'Bachelor',
        'cp_gesamt': 120,
        'name': 'BWL',
        'regelstudienzeit': 6,
        'studiengang_id': 'SG02'},
    {   'abschluss': 'Bachelor',
        'cp_gesamt': 153,
        'name': 'Maschinenbau',
        'regelstudienzeit': 8,
        'studiengang_id': 'SG03'},
    {   'abschluss': 'Bachelor',
        'cp_gesamt': 132,
        'name': 'Psychologie',
        'regelstudienzeit': 7,
        'studiengang_id': 'SG04'},
    {   'abschluss': 'Bachelor',
        'cp_gesamt': 132,
        'name': 'Soziale Arbeit',
        'regelstudienzeit': 7,
        'studiengang_id': 'SG05'}]

SUPPORT_ANGEBOTE = [   {   'angebot_id': 'SUP01',
        'fachbezogen': True,
        'kosten_h': 30,
        'name': 'Mathe-Tutorium',
        'typ': 'fachlich'},
    {   'angebot_id': 'SUP02',
        'fachbezogen': True,
        'kosten_h': 30,
        'name': 'Programmier-Lerngruppe',
        'typ': 'fachlich'},
    {   'angebot_id': 'SUP03',
        'fachbezogen': True,
        'kosten_h': 30,
        'name': 'Statistik-Repetitorium',
        'typ': 'fachlich'},
    {   'angebot_id': 'SUP04',
        'fachbezogen': True,
        'kosten_h': 30,
        'name': 'Schreibwerkstatt',
        'typ': 'fachlich'},
    {   'angebot_id': 'SUP05',
        'fachbezogen': True,
        'kosten_h': 30,
        'name': 'Sprachkurs Englisch',
        'typ': 'fachlich'},
    {   'angebot_id': 'SUP06',
        'fachbezogen': True,
        'kosten_h': 30,
        'name': 'Examenscoaching',
        'typ': 'fachlich'},
    {   'angebot_id': 'SUP07',
        'fachbezogen': False,
        'kosten_h': 10,
        'name': 'Zeitmanagement-Workshop',
        'typ': 'ueberfachlich'},
    {   'angebot_id': 'SUP08',
        'fachbezogen': False,
        'kosten_h': 10,
        'name': 'Lerncoaching',
        'typ': 'ueberfachlich'},
    {   'angebot_id': 'SUP09',
        'fachbezogen': False,
        'kosten_h': 10,
        'name': 'Mentoring-Programm',
        'typ': 'ueberfachlich'},
    {   'angebot_id': 'SUP10',
        'fachbezogen': False,
        'kosten_h': 5,
        'name': 'Psychologische Beratung',
        'typ': 'psychosozial'},
    {   'angebot_id': 'SUP11',
        'fachbezogen': False,
        'kosten_h': 5,
        'name': 'Studienberatung',
        'typ': 'psychosozial'},
    {   'angebot_id': 'SUP12',
        'fachbezogen': False,
        'kosten_h': 15,
        'name': 'Peer-Support-Gruppe',
        'typ': 'psychosozial'}]

SUPPORT_KEYWORDS = [   ('mathematik', 'SUP01', 1.3),
    ('mathe', 'SUP01', 1.3),
    ('programmier', 'SUP02', 1.4),
    ('algorithm', 'SUP02', 1.0),
    ('software', 'SUP02', 0.8),
    ('statistik', 'SUP03', 1.4),
    ('methoden', 'SUP03', 0.9),
    ('empir', 'SUP03', 1.0),
    ('seminar', 'SUP04', 1.2),
    ('bachelorarbeit', 'SUP04', 1.5),
    ('projektarbeit', 'SUP04', 1.0),
    ('forschungsprojekt', 'SUP04', 1.1),
    ('wahlpflicht', 'SUP05', 0.6),
    ('bachelorarbeit', 'SUP06', 1.3),
    ('kolloquium', 'SUP06', 1.2)]

HZB_TYPEN = ['Allg. Hochschulreife', 'Fachhochschulreife', 'Fachgebundene HR', 'Berufl. Qualifikation']
HZB_GEWICHTE = [0.70, 0.20, 0.05, 0.05]
